# https://www.willianantunes.com/blog/2022/08/create-a-certificate-using-certbot-through-docker/
# docker-compose run certbot certonly -d <domain, ex. myserver.com> --manual --preferred-challenges dns --dry-run
version: "3.8"

services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./etc-letsencrypt:/etc/letsencrypt
      - ./var-lib-letsencrypt:/var/lib/letsencrypt
      - ./var-log-letsencrypt:/var/log/letsencrypt